### ISSUE TITLE
different object can not have same field name with different types

### ISSUE THREAD

**Issue by songdongsheng** [Erudika/para#11]
field 'content' in object type 'layout' is object type, and the other object type 'xxx' have field 'content' type is long:

2017-06-07 14:42:48,943 [WARN ] c.erudika.para.search.ElasticSearch - null
java.lang.IllegalArgumentException: [properties.content] is defined as an object in mapping [layout] but this name is already used for a field in other types
        at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:510)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:376)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:320)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:306)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by songdongsheng** [comment]
Elasticsearch folks said :  Fields with the same name in different types in the same index should have the same mapping. Previously, this has been advised as "best practice", but relying on advice has proved insufficient. Instead we need to enforce this in the API.

https://github.com/mozilla/addons-server/issues/2850
https://github.com/elastic/elasticsearch/issues/8870
https://github.com/elastic/elasticsearch/issues/18450

**Comment by albogdano** [comment]
Hi, this is a limitation of Elasticsearch, not Para. I have plans to upgrade Para to ES 5+ for the next version, as well as removing it completely as a dependency. ES embedded mode is deprecated in v5. 
The workaround is to rename your field and this resolves the conflict. 

Another limitation of ES is when you have a field `content` of type `string` and later you try to change the mapping type to something else like `object` - ES won't allow it unless you reindex all your data. 

Also, reindexing in `embedded` mode is not currently supported in Para.

**Comment by songdongsheng** [comment]
Could you use one ES index per table module ? App usually have many tables, the have same filed name with different type looks reasonable.

**Comment by songdongsheng** [comment]
Could you use one ES index per table module ? App usually have many tables, the have same filed name with different type looks reasonable.

**Comment by albogdano** [comment]
Yes, I if you have a separate index for each table, there is less chance for a mapping conflict like this. When creating an app you can set `app.setSharingIndex(false)` - this will create a separate ES index for that app.

**Comment by songdongsheng** [comment]
Thanks, my root app already created with:

sharingIndex = false
sharingTable = false

Then this is IndexBasedDAO issue.

**Comment by albogdano** [comment]
Yes, `IndexBasedDAO` should only be used for local development and testing.

**Comment by albogdano** [comment]
**2018 UPDATE:** This is now fixed with the new "nested" indexing mode which prevents mapping explosions and allows two objects to have the same custom field with different types.
