### ISSUE TITLE
RuntimeException from Elastic Search DB

### ISSUE THREAD

**Issue by purushottam34** [Erudika/para#280]
Getting below error : 

 Failed to initialize Para.
java.lang.RuntimeException: null
	at com.erudika.para.server.utils.HealthUtils$1.isHealthy(HealthUtils.java:49)
	at com.erudika.para.server.utils.HealthUtils$1.onInitialize(HealthUtils.java:112)
	at com.erudika.para.core.utils.Para.initialize(Para.java:113)
	at com.erudika.para.server.ParaServer.initialize(ParaServer.java:153)
	at com.erudika.para.server.ParaServer.builder(ParaServer.java:399)
	at com.erudika.para.server.ParaServer.main(ParaServer.java:421)
	at com.erudika.para.jar.Run.main(Run.java:28)
	
	
It's working fine if we disable the **search_enabled** option.

 how can we make it work without disabling it? Please suggest

**Comment by albogdano** [comment]
There seems to be a bug in the `HealthUtils` class which caused the NPE. I fixed it now. Please wait for the new version of Para and update, or rebuild Para from the main branch and restart.
