### ISSUE TITLE
para-core 1.50.3 getting MockSearch issue

### ISSUE THREAD

**Issue by Sree-Durga-G** [Erudika/para#300]
**Error:** 
2024-11-11 10:13:30 [ERROR] Failed to initialize Para.
java.lang.UnsupportedOperationException: Not implemented.
	at com.erudika.para.core.search.MockSearch.findById(MockSearch.java:90)
	at com.erudika.para.server.aop.SearchQueryAspect.invoke(SearchQueryAspect.java:80)
	at com.erudika.para.server.utils.HealthUtils$1.performHealthCheck(HealthUtils.java:73)
	at com.erudika.para.server.utils.HealthUtils$1.onInitialize(HealthUtils.java:101)
	at com.erudika.para.core.utils.Para.initialize(Para.java:114)
	at com.erudika.para.server.ParaServer.initialize(ParaServer.java:148)
	at com.erudika.para.server.ParaServer.builder(ParaServer.java:399)
	at com.erudika.para.server.ParaServer.main(ParaServer.java:409)
	at com.erudika.para.jar.Run.main(Run.java:28)

Java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

**Comment by albogdano** [comment]
You are probably not starting Para from the correct jar file. There is a `para-jar` subfolder with the correct JAR.
