### ISSUE TITLE
Not able to boot para with elastic search config

### ISSUE THREAD

**Issue by arpanrnc** [Erudika/para#61]
Hi,

I have build para from master and am using para-search-elasticsearch 1.31.1 with the following config in application.conf

```
para.search = "ElasticSearch"
para.read_from_index = false
para.es.cors_enabled = false
para.es.discovery_type = "ec2"
para.es.discovery_group = "elasticsearch"
para.es.shards = 5
para.es.replicas = 1
para.es.dir = "data"
para.es.auto_expand_replicas = "0-1"
para.es.use_transportclient = false
para.es.transportclient_host = "<ip>"
para.es.transportclient_port = 9300
para.es.restclient_scheme = "http"
para.es.restclient_host = "<ip>"
para.es.restclient_port = 9200
para.es.sign_requests_to_aws = false
para.es.fail_on_indexing_errors = false

# asynchronous settings
para.es.async_enabled = false
para.es.bulk.size_limit_mb = 5
para.es.bulk.action_limit = 1000
para.es.bulk.concurrent_requests = 1
para.es.bulk.flush_interval_ms = 5000
para.es.bulk.backoff_initial_delay_ms = 50
para.es.bulk.max_num_retries = 8
para.es.bulk.flush_immediately = false

# proxy settings
para.es.proxy_enabled = false
para.es.proxy_path = "_elasticsearch"
para.es.proxy_reindexing_enabled = false
```

but on boot, I am getting the following error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: java.util.ServiceConfigurationError: com.erudika.para.search.Search: Provider com.erudika.para.search.ElasticSearch could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.erudika.para.search.SearchModule.loadExternalSearch(SearchModule.java:54)
	at com.erudika.para.search.SearchModule.configure(SearchModule.java:33)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.erudika.para.ParaServer.initialize(ParaServer.java:142)
	at com.erudika.para.ParaServer.runAsJAR(ParaServer.java:410)
	at com.erudika.para.ParaServer.main(ParaServer.java:419)
	at com.erudika.para.Run.main(Run.java:26)
	... 8 more
Caused by: java.util.ServiceConfigurationError: org.elasticsearch.plugins.spi.NamedXContentProvider: Provider org.elasticsearch.join.spi.ParentJoinNamedXContentProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.elasticsearch.client.RestHighLevelClient.getProvidedNamedXContents(RestHighLevelClient.java:1887)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:251)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:236)
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:228)
	at com.erudika.para.search.ElasticSearchUtils.getRESTClient(ElasticSearchUtils.java:285)
	at com.erudika.para.search.ElasticSearchUtils.initClient(ElasticSearchUtils.java:227)
	at com.erudika.para.search.ElasticSearch.<init>(ElasticSearch.java:124)
	at com.erudika.para.search.ElasticSearch.<init>(ElasticSearch.java:112)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:433)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 22 more
```

Any pointers ?

**Comment by albogdano** [comment]
I guess the plugin is missing some required dependencies. Did you compile the plugin yourself? You should use the shaded JAR file which packs all dependencies together and put that file inside `./lib` next to the Para JAR file.

**Comment by arpanrnc** [comment]
@albogdano I did not complie para-search-elasticsearch plugin. I am using the 1.31.1 release (by putting in lib folder and pointing to it at boot)

**Comment by albogdano** [comment]
What other files do you have in `./lib`? Maybe there's a conflict with another JAR.

**Comment by albogdano** [comment]
Closing due to inactivity.
